name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vanbuggenum/vanbuggenum/.github/workflows/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: "https://mellifluous-phoenix-5e25d6.netlify.app/index.xml"
